Use Jenkins base image to avoid workaround for Docker packaging limitations
cloudbees-oss/cjd-jcasc-demo pull request #2
Opened 2019-08-05 13:24 UTC by oleg-nenashev

This change works around limitations of Jenkins plugin management scripts from https://github.com/jenkinsci/docker which are not compatible with CloudBees Jenkiuns Distribution 2.176.2.3 structure. Instead of trying to hack the image, let's use CJD WAR file as a drop-in replacement.

Works around:

* https://github.com/jenkinsci/docker/issues/857
* https://github.com/jenkinsci/docker/issues/861

Once the issues are fixed, we can easily return to the CJD base image

2019-08-05 14:29 UTC, MRamonLeon approved these changes
This approach looks better to me.

2019-08-06 05:04 UTC, jphartley requested changes
Overall looks like a much cleaner approach, though I am not an expert on this. Shorter looks beter. Just maybe add a little more comments.

2019-08-06 05:04 UTC, jphartley commented on Dockerfile
> +COPY --from=war_source /usr/share/cloudbees-jenkins-distribution/cloudbees-jenkins-distribution.war /usr/share/jenkins/jenkins.war
Only real comment is maybe add one line of comment here to explain to the user why you are doing this. This isn't super obvious to myself who is a relatively inexperienced Jenkins/CJD user.

2019-08-06 07:42 UTC, oleg-nenashev commented
@jphartley  done

2019-08-06 08:32 UTC, varyvol approved these changes

2019-08-06 10:53 UTC, jphartley approved these changes
Looks good now

2019-08-06 10:53 UTC, jphartley commented on Dockerfile
> +COPY --from=war_source /usr/share/cloudbees-jenkins-distribution/cloudbees-jenkins-distribution.war /usr/share/jenkins/jenkins.war
Thanks for the change

2019-08-06 12:40 UTC, merged